### ISSUE TITLE
Color picker not working

### ISSUE THREAD

**Issue by robertdevore** [ahmadawais/WP-OOP-Settings-API#8]
Example screenshot

![color-picker](https://user-images.githubusercontent.com/9917957/37812341-e39f14de-2e35-11e8-9900-dcc20d6a13e6.jpg)

**Comment by ahmadawais** [comment]
That must be due to the latest Color Picker update. Try and fix that :)

**Comment by robertdevore** [comment]
:+1: That's why I opened up the issue, so I won't forget to get back to it :smile:

**Comment by igorbenic** [comment]
Not sure if this was added after it, but if not, just uncommenting it might fix this issue :)

https://github.com/ahmadawais/WP-OOP-Settings-API/blob/master/class-wp-osa.php#L785

**Comment by robertdevore** [comment]
@igorbenic tried that, but didn't seem to fix it. I see a `.wpColorPicker is not a function` notice in the console. Going to look into it later.
